---
- name: Install globus, globusconnectpersonal, and setup an endpoint on host
  hosts: localhost
  remote_user: root

  roles:
    #- InitializeGlobusEndpoint
    - ansible-simpleca
    - ansible-gridftp

#?
