#!/bin/bash
#
# Copyright 2010-2013 University of Chicago
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CONFIG="${HOME}/.globusonline"

usage () {
	echo "Removes Globus Connect Personal configuration files"
    echo
    echo "Usage:"
    echo "  sh remove_globusconnect"
}

delete () {
	echo  "Are you sure you want to remove your Globus Connect Personal configuration?\nA new endpoint will have to be created to continue using GCP afterwards."
	read -p "[Y/N]?" -r
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	    rm -rf "${CONFIG}"
	fi
}


while [ $# -gt 0 ]; do
    case "$1" in
	-help)
		usage
		exit 0
		;;
	*)
		usage
		exit 0
		;;
	esac
done

delete

exit 0
